"""accrete command line.

  accrete init DIR                      create an empty application instance
  accrete apply DIR CHANGE.yaml [--dry-run] [--json]
  accrete revert DIR SEQ [--dry-run] [--force]
  accrete context DIR                   one-screen overview: model, users, sample records, ledger, semantics
  accrete show DIR [ENTITY]             compact summary of the current model
  accrete log DIR [SEQ]                 ledger: every change, its verdict and report
  accrete call DIR METHOD PATH [--as USER] [--body JSON] [--now ISO]   run one request
  accrete check DIR                     re-validate the model and all data
  accrete snapshot DIR / upgrade-check DIR   engine-upgrade gate (golden responses; also recorded on every commit)
  accrete serve DIR [--port 8000]       run the application (API + UI)
  accrete demo                          live demonstration (real changes and checks)
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import sys

from . import change as C
from . import model as M
from . import runtime as R
from .store import Store

ENTRY = '''"""Application instance entry point (generated by accrete init)."""
import os

from accrete.wsgi import make_app


def create_app():
    return make_app(os.path.dirname(os.path.abspath(__file__)))
'''


def cmd_init(a):
    os.makedirs(a.dir, exist_ok=True)
    with open(os.path.join(a.dir, "app_entry.py"), "w") as fh:
        fh.write(ENTRY)
    os.makedirs(os.path.join(a.dir, "changes"), exist_ok=True)
    Store(a.dir).close()
    print(f"initialised {a.dir}")


def print_report(rep, out=sys.stdout):
    v = rep.get("verdict")
    print(f"verdict: {v.upper()}" + (f"  (ledger #{rep['seq']})" if rep.get("seq") else ""), file=out)
    if rep.get("reason"):
        print(f"reason: {rep['reason']}", file=out)
    if rep.get("request"):
        print(f"request: {rep['request']}", file=out)
    for n in rep.get("what_happened", []):
        print(f"  - {n}", file=out)
    for w in rep.get("warnings", []):
        print(f"  ! {w}", file=out)
    sc = rep.get("static_check", {}).get("problems") or []
    for p in sc[:20]:
        print(f"  static: {p}", file=out)
    dc = rep.get("data_check", {})
    for p in (dc.get("violations") or [])[:20]:
        print(f"  data: {p['count']} {p['entity']} record(s) violate {p['field_or_rule']}: {p['message']} "
              f"(e.g. ids {p['examples']})", file=out)
    fp = rep.get("footprint")
    if fp:
        print(f"  direct footprint: {', '.join(fp['direct'])}", file=out)
        if fp.get("consequences"):
            print(f"  possible consequences (dependents): {', '.join(fp['consequences'])}", file=out)
    rp = rep.get("replay")
    if rp and "probes" in rp:
        print(f"  replay: {rp['probes']} requests: {rp['identical']} identical, {rp['direct']} changed as intended, "
              f"{rp['acknowledged']} acknowledged consequences, {rp['consequence']} UNACKNOWLEDGED consequences, "
              f"{rp['unexplained']} unexplained", file=out)
        for ex in rp.get("examples", []):
            print(f"    {ex['kind'].upper()} {ex['request']}: {ex['before'][0]} -> {ex['after'][0]} [{', '.join(ex['labels'])}]", file=out)
            print(f"        before: {ex['before'][1][:160]}", file=out)
            print(f"        after:  {ex['after'][1][:160]}", file=out)
    exps = rep.get("expectations", []) or []
    for e in exps:
        if not e["passed"]:
            print(f"  expect FAIL {e['name']} {e['detail']}", file=out)
    if exps:
        print(f"  expectations: {sum(1 for e in exps if e['passed'])}/{len(exps)} passed", file=out)
    if rep.get("timings"):
        print(f"  timings (ms): {rep['timings']}", file=out)
    for h in next_steps(rep):
        print(f"NEXT: {h}", file=out)


def next_steps(rep):
    """Concrete advice for the most likely next action after a report."""
    v = rep.get("verdict")
    if v in ("committed", "dry-run passed"):
        return [] if v == "committed" else ["all checks passed; run the same command without --dry-run to commit"]
    out = []
    reason = rep.get("reason", "")
    if reason.startswith("operator"):
        out.append("fix that operator (names: `accrete context APP`; operator keys: GUIDE.md 'Operator reference'); nothing was changed")
    if (rep.get("static_check") or {}).get("problems"):
        out.append("each 'static:' line names an expression that no longer resolves; change or remove it in the same change file")
    for p in (rep.get("data_check") or {}).get("violations") or []:
        out.append(f"{p['count']} existing {p['entity']} record(s) fail `{p['field_or_rule']}`: add `backfill:` to the add_field, an "
                   f"`update_records` op, a `convert:`/`map:` on change_field, or `existing: exempt` on the constraint")
    rp = rep.get("replay") or {}
    if rp.get("consequence"):
        labs = sorted(rp.get("consequence_labels", {}))
        out.append(f"if these side-effects are intended (see CONSEQUENCE examples), add: consequences: [{', '.join(labs)}]; "
                   f"if not, change the operators so those features keep their behaviour")
    if rp.get("unexplained"):
        out.append("UNEXPLAINED differences: behaviour changed somewhere the operators do not touch; inspect the examples "
                   "(a crash 500 means an expression fails at runtime for those records)")
    if any(not e["passed"] for e in rep.get("expectations") or []):
        out.append("an expectation failed: either the change does not do what the example says, or the example is wrong")
    return out or ["read the reason above; a rejected change alters nothing"]


def write_notes(rep, path):
    """CHANGE_NOTES.md from the change and its pipeline report (what the change was, what was checked)."""
    rp = rep.get("replay") or {}
    exps = rep.get("expectations") or []
    lines = [f"# {rep.get('request', '').strip()}", "",
             f"Interpretation: {rep.get('interpretation') or '(as requested)'}", "",
             f"Applied with `accrete apply` as ledger change #{rep.get('seq')} ({rep.get('verdict')}).", "",
             "What changed:"]
    lines += [f"- {n}" for n in rep.get("what_happened", [])]
    fp = rep.get("footprint") or {}
    if fp.get("declared"):
        lines += ["", f"Acknowledged consequences: {', '.join(fp['declared'])}"]
    lines += ["", "Verification (accrete pipeline):",
              f"- static check: {len((rep.get('static_check') or {}).get('problems') or [])} problems",
              f"- data check: {(rep.get('data_check') or {}).get('records', '?')} existing records re-validated, "
              f"{len((rep.get('data_check') or {}).get('violations') or [])} violations"]
    if "probes" in rp:
        lines.append(f"- replay: {rp['probes']} requests on old and new versions: {rp['identical']} identical, {rp['direct']} changed as "
                     f"intended, {rp['acknowledged']} acknowledged consequences, {rp['unexplained']} unexplained")
    lines.append(f"- expectations: {sum(1 for e in exps if e['passed'])}/{len(exps)} passed")
    lines += [f"  - {e['name']}" for e in exps]
    with open(path, "w") as fh:
        fh.write("\n".join(lines) + "\n")


def cmd_apply(a):
    doc, base = C.load_change(a.change)
    now = dt.datetime.fromisoformat(a.now) if a.now else None
    rep = C.apply_change(a.dir, doc, dry_run=a.dry_run, base_dir=base, now=now)
    _save_report(a.dir, rep, a.change)
    if a.notes and rep["verdict"] == "committed":
        write_notes(rep, a.notes)
    if a.json:
        print(json.dumps(rep, indent=1, default=str))
    else:
        print_report(rep)
    return 0 if rep["verdict"] in ("committed", "dry-run passed") else 2


def _save_report(directory, rep, source):
    os.makedirs(os.path.join(directory, "changes"), exist_ok=True)
    tag = rep.get("seq") or "dry"
    path = os.path.join(directory, "changes", f"report-{tag}-{rep['verdict'].replace(' ', '-')}.json")
    with open(path, "w") as fh:
        json.dump(dict(rep, source=os.path.abspath(source) if source else None), fh, indent=1, default=str)


def cmd_revert(a):
    rep = C.revert(a.dir, a.seq, dry_run=a.dry_run, force=a.force)
    if rep.get("verdict") in ("committed", "dry-run passed", "rejected") and "started" in rep:
        _save_report(a.dir, rep, None)
    print_report(rep)
    return 0 if rep["verdict"] in ("committed", "dry-run passed") else 2


def cmd_show(a):
    st = Store(a.dir)
    model, world = st.load()
    st.close()
    if model is None:
        print("empty application")
        return 0
    if model.get("users"):
        ue = model["entities"][model["users"]["entity"]]
        print(f"users: {ue['name']} identified by {ue['fields'][model['users']['key']]['name']}")
    for e in model["entities"].values():
        if a.entity and e["name"] != a.entity:
            continue
        n = len(R.records(world, e["id"]))
        disp = e["fields"].get(e.get("display") or "", {}).get("name")
        print(f"\n{e['name']}  ({n} records)" + (f"  shown by {disp} where referenced" if disp else ""))
        for f in M.ordered_fields(e):
            kind = f["type"] + (f" {f.get('of')}" if f["type"] == "list" else "")
            bits = [kind + (f" {model['entities'][f['ref']]['name']}" if M.refers_to(f) and f.get('ref') in model['entities'] else "")
                    + (f" {'|'.join(f['values'])}" if "enum" in kind else "")]
            for k in ("required", "unique", "system", "distinct"):
                if f.get(k):
                    bits.append(k)
            for k in ("default", "computed", "read_if", "write_if"):
                if f.get(k):
                    bits.append(f"{k}: {f[k]}")
            print(f"  {f['name']}: {'; '.join(bits)}")
        for r in M.RULES:
            if e["rules"].get(r) not in (None, "", "True"):
                print(f"  rule {r}: {e['rules'][r]}")
        for c in e["constraints"].values():
            print(f"  constraint {c['name']}: {c['expr']}" + (f"  [{len(c['exempt'])} exempt]" if c.get("exempt") else ""))
        for act in e["actions"].values():
            ps = ", ".join(f"{p}:{s['type']}" + ("!" if s.get("required") else "") for p, s in act["params"].items())
            print(f"  action {act['name']}({ps})  allow: {act.get('allow')}  guard: {act.get('guard')}")
            for eff in act["effects"]:
                print(f"      effect: {json.dumps(eff)}")
        for t in e["triggers"].values():
            print(f"  trigger {t['name']} on {t['on']} when {t.get('when')}: {json.dumps(t['effects'])}")
    return 0


def cmd_context(a):
    """Everything an implementer needs to start a change, in one screen: the model (as `show`),
    the users by role, two sample records per entity as the API returns them, the recent
    ledger, and the exact request semantics."""
    st = Store(a.dir)
    model, world = st.load()
    ledger = st.ledger()
    st.close()
    if model is None:
        print("empty application (accrete init was run, nothing applied yet)")
        return 0
    cmd_show(argparse.Namespace(dir=a.dir, entity=None))
    now = R.parse_now(a.now)
    ue = M.user_entity(model)
    users = []
    if ue:
        key = ue["fields"][model["users"]["key"]]["name"]
        groups = {}
        for rid in sorted(R.records(world, ue["id"])):
            ctx = R.Ctx(model, world, None, now)
            rec = R.Rec(ctx, ue, rid)
            sig = []
            for f in M.ordered_fields(ue):
                if f["type"] in ("enum", "bool") and not f.get("computed"):
                    try:
                        sig.append(f"{f['name']}={R.to_json(getattr(rec, f['name']))}")
                    except Exception:  # noqa: BLE001
                        pass
            groups.setdefault(", ".join(sig), []).append(f"{getattr(rec, key)}(id {rid})")
        print("\nusers (X-User = " + key + ") grouped by their enum/bool fields:")
        for sig, names in groups.items():
            print(f"  [{sig}] {', '.join(names[:8])}" + (f" ... +{len(names) - 8}" if len(names) > 8 else ""))
            users.append(names[0].split("(")[0])
    print("\nsample records (as the API returns them to the first user who may read them):")
    for e in model["entities"].values():
        ids = sorted(R.records(world, e["id"]))
        for rid in ids[:2]:
            shown = None
            for u in users or [None]:
                status, body = R.handle(model, world, "GET", f"/api/{e['name']}/{rid}", {}, None, u, now)
                if status == 200:
                    shown = (u, body)
                    break
            if shown:
                print(f"  {e['name']} {rid} (as {shown[0]}): {json.dumps(shown[1])[:300]}")
    print("\nrecent ledger:")
    for e in ledger[-5:]:
        print(f"  #{e['seq']} {e['verdict']:9} {e.get('request', '')[:100]}")
    print("""
request semantics (exact):
  list: GET /api/E -> records the caller may read, ?field=value exact match (refs by id, true/false, null); unknown field -> 400
  create: 401 user, 404 E, 403 create rule / write_if, 409 create_guard, 400 input errors / defaults / constraints
  update: 404 record, 403 read+update rule / write_if, 409 update_guard, 400 input / constraints
  delete: 404, 403 read+delete rule, 409 delete_guard / still referenced (on_delete restrict)
  action: 404, 403 allow, 409 guard, 400 params; effects run atomically (any failure undoes everything)
  UI: /ui/E list, /ui/E/ID detail (action forms only where allow AND guard hold), /ui/E/new (403 if create rule false)
next: write changes/NNNN-name.yaml with request, interpretation, ops, expect (API and ui: checks), then
      accrete apply APP FILE --notes APP/CHANGE_NOTES.md   (atomic: a rejected change alters nothing)""")
    return 0


def cmd_snapshot(a):
    n = C.snapshot(a.dir)
    print(f"recorded {n} golden responses with engine {C.engine_version()}")
    return 0


def cmd_upgrade_check(a):
    rep = C.upgrade_check(a.dir)
    print(f"upgrade check: {rep['verdict']}" + (f" ({rep.get('differences')} of {rep.get('probes')} responses differ; "
          f"recorded with engine {rep.get('recorded_with_engine')}, now {rep.get('current_engine')})" if "probes" in rep else ""))
    if rep.get("reason"):
        print(rep["reason"])
    for ex in rep.get("examples", []):
        print(f"  {ex['request']}: {ex['before'][0]} -> {ex['after'][0]}")
        print(f"      before: {ex['before'][1][:160]}")
        print(f"      after:  {ex['after'][1][:160]}")
    return 0 if rep["verdict"] == "same" else 2


def cmd_log(a):
    st = Store(a.dir)
    led = st.ledger()
    st.close()
    for e in led:
        if a.seq and e["seq"] != a.seq:
            continue
        if a.seq:
            print(json.dumps(e, indent=1, default=str))
        else:
            extra = f" reverted by #{e['reverted_by']}" if e.get("reverted_by") else ""
            print(f"#{e['seq']} {e['verdict']:9} {e.get('kind', 'change'):6} {e.get('request', '')[:90]}{extra}")
    return 0


def cmd_call(a):
    st = Store(a.dir)
    model, world = st.load()
    now = R.parse_now(a.now)
    path, _, qs = a.path.partition("?")
    from urllib.parse import parse_qsl
    body = json.loads(a.body) if a.body else ({} if a.method.upper() in ("POST", "PATCH") else None)
    status, out, ctx = R.handle_full(model, world, a.method.upper(), path, dict(parse_qsl(qs)), body, a.user, now)
    if a.commit and (ctx.journal or len(world["outbox"]) > ctx.outbox_mark):
        st.save_changes(model, world, ctx.journal, ctx.outbox_mark)
    st.close()
    print(status)
    print(json.dumps(out, indent=1) if out is not None else "")
    return 0


def cmd_check(a):
    st = Store(a.dir)
    model, world = st.load()
    st.close()
    probs = M.check(model) if model else ["no model"]
    viol = C.data_violations(model, world, dt.datetime.utcnow()) if model else []
    for p in probs:
        print("static:", p)
    for v in viol:
        print("data:", v)
    print("ok" if not probs and not viol else "problems found")
    return 0 if not probs and not viol else 2


def cmd_serve(a):
    from wsgiref.simple_server import make_server

    from .wsgi import make_app
    app = make_app(a.dir)
    print(f"serving {a.dir} on http://127.0.0.1:{a.port}/ui/  (add ?as=<username> to act as a user)")
    make_server("127.0.0.1", a.port, app).serve_forever()


def cmd_demo(a):
    from . import demo
    return demo.run(keep=a.keep, pause=a.pause)


def main(argv=None):
    p = argparse.ArgumentParser(prog="accrete", description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest="cmd", required=True)
    s = sub.add_parser("init")
    s.add_argument("dir")
    s = sub.add_parser("apply")
    s.add_argument("dir")
    s.add_argument("change")
    s.add_argument("--dry-run", action="store_true")
    s.add_argument("--json", action="store_true")
    s.add_argument("--now", help="current time for evaluating defaults during the change")
    s.add_argument("--notes", help="on commit, write a CHANGE_NOTES.md-style summary to this path")
    s = sub.add_parser("revert")
    s.add_argument("dir")
    s.add_argument("seq", type=int)
    s.add_argument("--dry-run", action="store_true")
    s.add_argument("--force", action="store_true")
    s = sub.add_parser("show")
    s.add_argument("dir")
    s.add_argument("entity", nargs="?")
    s = sub.add_parser("context", help="one-screen overview for starting a change")
    s.add_argument("dir")
    s.add_argument("--now")
    s = sub.add_parser("snapshot", help="record golden responses for the engine-upgrade check")
    s.add_argument("dir")
    s = sub.add_parser("upgrade-check", help="replay golden responses against the installed engine")
    s.add_argument("dir")
    s = sub.add_parser("log")
    s.add_argument("dir")
    s.add_argument("seq", type=int, nargs="?")
    s = sub.add_parser("call")
    s.add_argument("dir")
    s.add_argument("method")
    s.add_argument("path")
    s.add_argument("--as", dest="user")
    s.add_argument("--body")
    s.add_argument("--now")
    s.add_argument("--commit", action="store_true", help="persist the effects of this request")
    s = sub.add_parser("check")
    s.add_argument("dir")
    s = sub.add_parser("serve")
    s.add_argument("dir")
    s.add_argument("--port", type=int, default=8000)
    s = sub.add_parser("demo", help="live demonstration on a fresh copy of the library app")
    s.add_argument("--keep", help="directory for the demo instance (default: a temp dir)")
    s.add_argument("--pause", action="store_true")
    a = p.parse_args(argv)
    return {"init": cmd_init, "apply": cmd_apply, "revert": cmd_revert, "show": cmd_show, "log": cmd_log,
            "call": cmd_call, "check": cmd_check, "serve": cmd_serve, "demo": cmd_demo,
            "context": cmd_context, "snapshot": cmd_snapshot, "upgrade-check": cmd_upgrade_check}[a.cmd](a) or 0


if __name__ == "__main__":
    sys.exit(main())
