"""accrete command line.

  accrete init DIR                      create an empty application instance
  accrete apply DIR CHANGE.yaml [--dry-run] [--json]
  accrete revert DIR SEQ [--dry-run] [--force]
  accrete show DIR [ENTITY]             compact summary of the current model
  accrete log DIR [SEQ]                 ledger: every change, its verdict and report
  accrete call DIR METHOD PATH [--as USER] [--body JSON] [--now ISO]   run one request
  accrete check DIR                     re-validate the model and all data
  accrete serve DIR [--port 8000]       run the application (API + UI)
  accrete demo                          live demonstration (real changes and checks)
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import sys

from . import change as C
from . import model as M
from . import runtime as R
from .store import Store

ENTRY = '''"""Application instance entry point (generated by accrete init)."""
import os

from accrete.wsgi import make_app


def create_app():
    return make_app(os.path.dirname(os.path.abspath(__file__)))
'''


def cmd_init(a):
    os.makedirs(a.dir, exist_ok=True)
    with open(os.path.join(a.dir, "app_entry.py"), "w") as fh:
        fh.write(ENTRY)
    os.makedirs(os.path.join(a.dir, "changes"), exist_ok=True)
    Store(a.dir).close()
    print(f"initialised {a.dir}")


def print_report(rep, out=sys.stdout):
    v = rep.get("verdict")
    print(f"verdict: {v.upper()}" + (f"  (ledger #{rep['seq']})" if rep.get("seq") else ""), file=out)
    if rep.get("reason"):
        print(f"reason: {rep['reason']}", file=out)
    if rep.get("request"):
        print(f"request: {rep['request']}", file=out)
    for n in rep.get("what_happened", []):
        print(f"  - {n}", file=out)
    for w in rep.get("warnings", []):
        print(f"  ! {w}", file=out)
    sc = rep.get("static_check", {}).get("problems") or []
    for p in sc[:20]:
        print(f"  static: {p}", file=out)
    dc = rep.get("data_check", {})
    for p in (dc.get("violations") or [])[:20]:
        print(f"  data: {p['count']} {p['entity']} record(s) violate {p['field_or_rule']}: {p['message']} "
              f"(e.g. ids {p['examples']})", file=out)
    fp = rep.get("footprint")
    if fp:
        print(f"  direct footprint: {', '.join(fp['direct'])}", file=out)
        if fp.get("consequences"):
            print(f"  possible consequences (dependents): {', '.join(fp['consequences'])}", file=out)
    rp = rep.get("replay")
    if rp and "probes" in rp:
        print(f"  replay: {rp['probes']} requests: {rp['identical']} identical, {rp['direct']} changed as intended, "
              f"{rp['acknowledged']} acknowledged consequences, {rp['consequence']} UNACKNOWLEDGED consequences, "
              f"{rp['unexplained']} unexplained", file=out)
        for ex in rp.get("examples", []):
            print(f"    {ex['kind'].upper()} {ex['request']}: {ex['before'][0]} -> {ex['after'][0]} [{', '.join(ex['labels'])}]", file=out)
            print(f"        before: {ex['before'][1][:160]}", file=out)
            print(f"        after:  {ex['after'][1][:160]}", file=out)
    for e in rep.get("expectations", []) or []:
        print(f"  expect {'ok  ' if e['passed'] else 'FAIL'} {e['name']} {e['detail']}", file=out)
    if rep.get("timings"):
        print(f"  timings (ms): {rep['timings']}", file=out)


def cmd_apply(a):
    doc, base = C.load_change(a.change)
    now = dt.datetime.fromisoformat(a.now) if a.now else None
    rep = C.apply_change(a.dir, doc, dry_run=a.dry_run, base_dir=base, now=now)
    _save_report(a.dir, rep, a.change)
    if a.json:
        print(json.dumps(rep, indent=1, default=str))
    else:
        print_report(rep)
    return 0 if rep["verdict"] in ("committed", "dry-run passed") else 2


def _save_report(directory, rep, source):
    os.makedirs(os.path.join(directory, "changes"), exist_ok=True)
    tag = rep.get("seq") or "dry"
    path = os.path.join(directory, "changes", f"report-{tag}-{rep['verdict'].replace(' ', '-')}.json")
    with open(path, "w") as fh:
        json.dump(dict(rep, source=os.path.abspath(source) if source else None), fh, indent=1, default=str)


def cmd_revert(a):
    rep = C.revert(a.dir, a.seq, dry_run=a.dry_run, force=a.force)
    if rep.get("verdict") in ("committed", "dry-run passed", "rejected") and "started" in rep:
        _save_report(a.dir, rep, None)
    print_report(rep)
    return 0 if rep["verdict"] in ("committed", "dry-run passed") else 2


def cmd_show(a):
    st = Store(a.dir)
    model, world = st.load()
    st.close()
    if model is None:
        print("empty application")
        return 0
    if model.get("users"):
        ue = model["entities"][model["users"]["entity"]]
        print(f"users: {ue['name']} identified by {ue['fields'][model['users']['key']]['name']}")
    for e in model["entities"].values():
        if a.entity and e["name"] != a.entity:
            continue
        n = len(R.records(world, e["id"]))
        print(f"\n{e['name']}  ({n} records)")
        for f in M.ordered_fields(e):
            bits = [f["type"] + (f" {model['entities'][f['ref']]['name']}" if f["type"] == "ref" and f.get('ref') in model['entities'] else "")
                    + (f" {'|'.join(f['values'])}" if f["type"] == "enum" else "")]
            for k in ("required", "unique", "system"):
                if f.get(k):
                    bits.append(k)
            for k in ("default", "computed", "read_if", "write_if"):
                if f.get(k):
                    bits.append(f"{k}: {f[k]}")
            print(f"  {f['name']}: {'; '.join(bits)}")
        for r in M.RULES:
            if e["rules"].get(r) not in (None, "", "True"):
                print(f"  rule {r}: {e['rules'][r]}")
        for c in e["constraints"].values():
            print(f"  constraint {c['name']}: {c['expr']}" + (f"  [{len(c['exempt'])} exempt]" if c.get("exempt") else ""))
        for act in e["actions"].values():
            ps = ", ".join(f"{p}:{s['type']}" + ("!" if s.get("required") else "") for p, s in act["params"].items())
            print(f"  action {act['name']}({ps})  allow: {act.get('allow')}  guard: {act.get('guard')}")
            for eff in act["effects"]:
                print(f"      effect: {json.dumps(eff)}")
        for t in e["triggers"].values():
            print(f"  trigger {t['name']} on {t['on']} when {t.get('when')}: {json.dumps(t['effects'])}")
    return 0


def cmd_log(a):
    st = Store(a.dir)
    led = st.ledger()
    st.close()
    for e in led:
        if a.seq and e["seq"] != a.seq:
            continue
        if a.seq:
            print(json.dumps(e, indent=1, default=str))
        else:
            extra = f" reverted by #{e['reverted_by']}" if e.get("reverted_by") else ""
            print(f"#{e['seq']} {e['verdict']:9} {e.get('kind', 'change'):6} {e.get('request', '')[:90]}{extra}")
    return 0


def cmd_call(a):
    st = Store(a.dir)
    model, world = st.load()
    now = R.parse_now(a.now)
    path, _, qs = a.path.partition("?")
    from urllib.parse import parse_qsl
    body = json.loads(a.body) if a.body else ({} if a.method.upper() in ("POST", "PATCH") else None)
    status, out, ctx = R.handle_full(model, world, a.method.upper(), path, dict(parse_qsl(qs)), body, a.user, now)
    if a.commit and (ctx.journal or len(world["outbox"]) > ctx.outbox_mark):
        st.save_changes(model, world, ctx.journal, ctx.outbox_mark)
    st.close()
    print(status)
    print(json.dumps(out, indent=1) if out is not None else "")
    return 0


def cmd_check(a):
    st = Store(a.dir)
    model, world = st.load()
    st.close()
    probs = M.check(model) if model else ["no model"]
    viol = C.data_violations(model, world, dt.datetime.utcnow()) if model else []
    for p in probs:
        print("static:", p)
    for v in viol:
        print("data:", v)
    print("ok" if not probs and not viol else "problems found")
    return 0 if not probs and not viol else 2


def cmd_serve(a):
    from wsgiref.simple_server import make_server

    from .wsgi import make_app
    app = make_app(a.dir)
    print(f"serving {a.dir} on http://127.0.0.1:{a.port}/ui/  (add ?as=<username> to act as a user)")
    make_server("127.0.0.1", a.port, app).serve_forever()


def cmd_demo(a):
    from . import demo
    return demo.run(keep=a.keep, pause=a.pause)


def main(argv=None):
    p = argparse.ArgumentParser(prog="accrete", description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest="cmd", required=True)
    s = sub.add_parser("init")
    s.add_argument("dir")
    s = sub.add_parser("apply")
    s.add_argument("dir")
    s.add_argument("change")
    s.add_argument("--dry-run", action="store_true")
    s.add_argument("--json", action="store_true")
    s.add_argument("--now", help="current time for evaluating defaults during the change")
    s = sub.add_parser("revert")
    s.add_argument("dir")
    s.add_argument("seq", type=int)
    s.add_argument("--dry-run", action="store_true")
    s.add_argument("--force", action="store_true")
    s = sub.add_parser("show")
    s.add_argument("dir")
    s.add_argument("entity", nargs="?")
    s = sub.add_parser("log")
    s.add_argument("dir")
    s.add_argument("seq", type=int, nargs="?")
    s = sub.add_parser("call")
    s.add_argument("dir")
    s.add_argument("method")
    s.add_argument("path")
    s.add_argument("--as", dest="user")
    s.add_argument("--body")
    s.add_argument("--now")
    s.add_argument("--commit", action="store_true", help="persist the effects of this request")
    s = sub.add_parser("check")
    s.add_argument("dir")
    s = sub.add_parser("serve")
    s.add_argument("dir")
    s.add_argument("--port", type=int, default=8000)
    s = sub.add_parser("demo", help="live demonstration on a fresh copy of the library app")
    s.add_argument("--keep", help="directory for the demo instance (default: a temp dir)")
    s.add_argument("--pause", action="store_true")
    a = p.parse_args(argv)
    return {"init": cmd_init, "apply": cmd_apply, "revert": cmd_revert, "show": cmd_show, "log": cmd_log,
            "call": cmd_call, "check": cmd_check, "serve": cmd_serve, "demo": cmd_demo}[a.cmd](a) or 0


if __name__ == "__main__":
    sys.exit(main())
